# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f887b63fe7ce92467cb4adcfa63e0e9a251f1be18127a058878462a8071773fca4dceeff10b366cdbc1407dd95efea5ca2fbda3df593cf4c93d4934a560f538

test:
  secret_key_base: f066ab37b9d8283e128df9b2d9b8bad146861614b06990061b5a2b2c173fb4f5fef987d05142d093d4dbb8bbf22d9ba8511c08ad9b521d9683c24792ea35bd56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
